workspace:
  base: /go
  path: src/github.com/metalmatze/githubql_exporter

pipeline:
  build:
    image: golang:1.8
    commands:
      - make fmt
      - make vet
      - make lint
      - make test
      - make build

  docker:
    image: plugins/docker
    repo: metalmatze/githubql_exporter
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push

  release:
    image: golang:1.8
    commands:
      - make release
    when:
      event: tag

  docker:
    image: plugins/docker
    repo: metalmatze/githubql_exporter
    secrets: [ docker_username, docker_password ]
    tag: [ 0, 0.1 ]
    when:
      event: tag

  github:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    files: dist/*
    when:
      event: tag
